### ISSUE TITLE
Loading data with events

### ISSUE THREAD

**Issue by dafunkphenomenon** [nilsmehlhorn/ngx-observe#22]
Very interesting concept, however this only seems to work where data is loaded on when the component loads.
For example, if you have sections of the page the load data on a button click for example, the loading template will be on the screen for the entire duration until the user has clicked and data is loaded.

**Comment by nilsmehlhorn** [comment]
It should be possible to leave the observable undefined until the user has clicked a button. This should not show the loading template. You can try it out by modifying the [example](https://stackblitz.com/github/nilsmehlhorn/ngx-observe-example?file=src%2Fapp%2Fapp.component.ts), it'll only render "Loading" once you click "Create Observable":

```ts
export class AppComponent {

  value$: Observable<string>

  createError() {
    this.value$ = of("something went wrong").pipe(
      delay(2000),
      tap(() => {
        throw new Error("oops");
      })
    );
  }

  createSuccess() {
    this.value$ = of("Success").pipe(delay(2000));
  }
}
```
