### ISSUE TITLE
as not working as described in readme.md

### ISSUE THREAD

**Issue by MoxxiManagarm** [nilsmehlhorn/ngx-observe#5]
Thank you again for your great talk today on iJS! I loved the observable directive, which should solve some of my minor issues I have in my hobby project. I just included it and I have 1 minor issue found.

 `as` is not working as you describe in your readme.md. At least my IDE (Webstorm) is highlighting any property access on the object.
`<p *ngxObserve="myData$ as myData; before loadingTemplate; error errorTemplate">`
`myData.foo` foo was highlighted as unknown property  
However, `let` of course resolved the issue
`<p *ngxObserve="myData$; let myData; before loadingTemplate; error errorTemplate">`

**Comment by nilsmehlhorn** [comment]
Hey @MoxxiManagarm, thanks for the feedback!

It should only highlight it in the IDE though, right? Or does it also error in the Angular CLI compilation process?

The process of informing the language service about context properties wasn't clearly documented, I basically mimicked what ngIf did at that point, resulting in these two lines:
https://github.com/nilsmehlhorn/ngx-observe/blob/master/projects/ngx-observe/src/lib/ngx-observe.directive.ts#L46
https://github.com/nilsmehlhorn/ngx-observe/blob/master/projects/ngx-observe/src/lib/ngx-observe.directive.ts#L139

I'll look into it, maybe something changed

**Comment by nilsmehlhorn** [comment]
I'm pretty sure this is only related to the language service integration, the Ivy template checking works fine for me

Would you mind trying it with this prerelease?
https://www.npmjs.com/package/ngx-observe/v/1.1.1-context.0

```bash
npm i ngx-observe@1.1.1-context.0
```

**Comment by MoxxiManagarm** [comment]
Gonna check later, thank you

**Comment by bbarry** [comment]
This issue appears in VsCode sometimes also...

It is absolutely related to the language service. This bug: https://github.com/angular/angular/issues/37119 is about the documentation for the context guards (which is sorta fixed now in that it isn't just missing halfway through a paragraph but could still be considerably improved). In trying to deduce how the underlying functionality works I've hit the languages service `unknown` type issue repeatedly while the actual compilation works fine.

see also: https://github.com/angular/vscode-ng-language-service/issues/880

**Comment by nilsmehlhorn** [comment]
Thanks for chiming in @bbarry, I actually just read that issue and considered reaching out to you, funny that you found your way here first!

Personally, the docs regarding template contexts don't seem very "fixed" to me - still pretty clueless about that topic. IMHO the compilation process seems way too complex in and of itself, but that's even another issue.

The prerelease linked above is based on your suggestions. I replaced `unknown` with `any`, which hopefully resolves the IDE error, though it still doesn't seem to provide one with proper autocompletion. Actually, I don't even get an error in VSC, just no autocompletion. It might be the case that IntelliJ is "better" at this, although that might mean they're not using just the plain language service.

**Comment by bbarry** [comment]
I can confirm that the prerelease does fix the issue for me and the compilation errors (and the type fix in the guard uncovered 2 bugs in my code) when you get the types wrong are still there. I don't have Webstorm to check there.
